"""Tehran's real neighborhood (محله) polygons and the Persian name resolution
that maps free text onto them.

Two source files, joined on the shared ``key`` field:

- ``matched_neighborhoods.geojson`` -- one polygon per neighborhood, carrying
  ``key``, ``title`` and ``search_keywords``.
- ``paired_neighborhoods.json`` -- the same 258 neighborhoods with their
  ``title``/``subtitle``/``search_keywords`` as shown in a listings UI.

A third file, ``gap_neighborhoods.geojson``, covers the third of Tehran those
two leave empty: curated polygons that never matched a key, plus land that was
inside no neighborhood at all, named and keyworded from OpenStreetMap by
``app.data.build_gap_neighborhoods``. It is merged in here rather than folded
into the files above, so the curated sources stay exactly as they were
received and the generated coverage can be rebuilt or dropped on its own. A
key defined in both wins from the curated file.

``search_keywords`` is what makes conversational search work: it lists the
streets and landmarks people actually name when they mean a neighborhood
("سئول، فجر، ونک، ..." for آرارات), which is rarely the neighborhood's own
title. Resolution therefore matches against titles *and* keywords, and always
returns the stable ``key`` -- polygons are looked up by key, never by name.
"""

import json
import re
from functools import lru_cache
from pathlib import Path
from typing import NamedTuple, Optional

from shapely.geometry import Point, shape
from shapely.geometry.base import BaseGeometry

from app.core.normalizers import normalize_for_match, squash_for_match
from app.spatial import landmarks

_DATA_DIR = Path(__file__).resolve().parent.parent / "data"
_POLYGONS_PATH = _DATA_DIR / "matched_neighborhoods.geojson"
_PAIRED_PATH = _DATA_DIR / "paired_neighborhoods.json"
# Generated by app.data.divar_preprocess: Divar neighborhood names that have
# no polygon of their own, each attached to the polygon its listings actually
# fall inside. Kept in its own file so the two curated sources above are never
# rewritten, and merged in as extra keywords below.
_ALIASES_PATH = _DATA_DIR / "neighborhood_aliases.json"
# Generated by app.data.build_gap_neighborhoods; absent until it has been run,
# in which case the map simply falls back to the curated coverage.
_GAP_PATH = _DATA_DIR / "gap_neighborhoods.geojson"

# Persian/Arabic comma and the usual separators show up inside
# search_keywords; splitting on them yields the individual landmark phrases.
_KEYWORD_SPLIT = re.compile(r"[،,؛;/\|\n]+")

def _norm(text: str) -> str:
    """Normalization used for *matching* names, as opposed to display."""
    return normalize_for_match(text)


# Substring matching below this length produces coincidental hits: "ارم" is a
# real neighborhood and also sits inside "نارمک".
_MIN_CONTAINMENT_LENGTH = 5


def _squash(text: str) -> str:
    """`_norm` with spacing removed entirely -- the form in which "یوسف آباد"
    and "یوسف‌آباد" finally compare equal."""
    return squash_for_match(text)


class Neighborhood(NamedTuple):
    key: str
    title: str
    subtitle: str
    keywords: tuple[str, ...]
    polygon: BaseGeometry
    center_lat: float
    center_lon: float
    min_lat: float
    min_lon: float
    max_lat: float
    max_lon: float


def _split_keywords(raw: str) -> tuple[str, ...]:
    parts = (_norm(part).strip() for part in _KEYWORD_SPLIT.split(raw or ""))
    return tuple(part for part in parts if part)


def _load_paired() -> dict[str, dict]:
    payload = json.loads(_PAIRED_PATH.read_text(encoding="utf-8"))
    return {child["data"]["key"]: child["data"] for child in payload.get("children", [])}


def _load_aliases() -> dict[str, list[str]]:
    """Extra names per neighborhood key, or {} before the crawl is processed."""
    if not _ALIASES_PATH.exists():
        return {}
    payload = json.loads(_ALIASES_PATH.read_text(encoding="utf-8"))
    return {str(key): list(names) for key, names in payload.get("aliases", {}).items()}


def _build(feature: dict, paired: dict[str, dict], aliases: dict[str, list[str]]) -> Optional[Neighborhood]:
    props = feature.get("properties", {})
    key = props.get("key")
    if not key:
        return None

    polygon = shape(feature["geometry"])
    if not polygon.is_valid:
        # A handful of the source rings self-intersect, which makes every
        # downstream contains()/union() call raise. buffer(0) is the
        # standard GEOS repair and leaves valid polygons untouched.
        polygon = polygon.buffer(0)
    if polygon.is_empty:
        return None

    extra = paired.get(str(key), {})
    # The centroid of a concave neighborhood can fall outside it;
    # representative_point() is guaranteed to be inside, which matters
    # because this is where the map draws the neighborhood's label.
    anchor = polygon.representative_point()
    min_lon, min_lat, max_lon, max_lat = polygon.bounds

    return Neighborhood(
        key=str(key),
        title=props.get("title") or extra.get("title") or "",
        subtitle=extra.get("subtitle") or props.get("subtitle") or "",
        # The curated landmarks plus every Divar neighborhood name that
        # resolves here, so searching Divar's vocabulary finds our
        # polygon even where Divar subdivides more finely than we can.
        keywords=_split_keywords(props.get("search_keywords") or extra.get("search_keywords") or "")
        + tuple(_norm(alias) for alias in aliases.get(str(key), [])),
        polygon=polygon,
        center_lat=anchor.y,
        center_lon=anchor.x,
        min_lat=min_lat,
        min_lon=min_lon,
        max_lat=max_lat,
        max_lon=max_lon,
    )


def _features(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return json.loads(path.read_text(encoding="utf-8")).get("features", [])


def _load_neighborhoods() -> list[Neighborhood]:
    paired = _load_paired()
    aliases = _load_aliases()

    neighborhoods: list[Neighborhood] = []
    seen: set[str] = set()
    # Curated first: a key present in both files keeps its curated polygon.
    for feature in _features(_POLYGONS_PATH) + _features(_GAP_PATH):
        neighborhood = _build(feature, paired, aliases)
        if neighborhood is None or neighborhood.key in seen:
            continue
        seen.add(neighborhood.key)
        neighborhoods.append(neighborhood)
    return neighborhoods


NEIGHBORHOODS: list[Neighborhood] = _load_neighborhoods()
_BY_KEY: dict[str, Neighborhood] = {n.key: n for n in NEIGHBORHOODS}
_BY_TITLE: dict[str, Neighborhood] = {_squash(n.title): n for n in NEIGHBORHOODS if n.title}
# Two real places can share a name -- there is a کوهسار in منطقه ۲ and another
# in منطقه ۴ -- so their titles carry the district that tells them apart. That
# qualifier is not something anyone types, though, so each is also indexed
# under its bare name here. Where several share it, the largest wins: it is
# the one a bare "کوهسار" most likely means, and it is a far better answer
# than an unrelated neighborhood that merely has a street by that name.
_QUALIFIER = re.compile(r"\s*\([^)]*\)\s*$")
_BY_BASE_TITLE: dict[str, Neighborhood] = {}
for _neighborhood in sorted(NEIGHBORHOODS, key=lambda n: n.polygon.area):
    _base = _squash(_QUALIFIER.sub("", _neighborhood.title))
    if _base and _base not in {_squash(n.title) for n in NEIGHBORHOODS}:
        _BY_BASE_TITLE[_base] = _neighborhood

_BY_KEYWORD: dict[str, Neighborhood] = {
    keyword: neighborhood
    for neighborhood in reversed(NEIGHBORHOODS)  # earlier entries win on collision
    for keyword in map(_squash, neighborhood.keywords)
    if keyword
}


_METERS_PER_DEGREE_LAT = 111_320.0


def area_sqkm(neighborhood: Neighborhood) -> float:
    """The neighborhood's footprint in square kilometres.

    The polygon's own area is in square degrees, which is not a unit anything
    outside shapely can use and is anisotropic besides -- a degree of
    longitude is only ~0.81 of a degree of latitude at Tehran's 35.7 deg. Both
    axes are converted at the shape's own latitude, which is accurate to well
    under a percent over a محله-sized footprint.
    """
    import math

    lat = neighborhood.center_lat
    per_deg_lon_km = _METERS_PER_DEGREE_LAT * math.cos(math.radians(lat)) / 1000.0
    return neighborhood.polygon.area * (_METERS_PER_DEGREE_LAT / 1000.0) * per_deg_lon_km


def get(key: str) -> Optional[Neighborhood]:
    return _BY_KEY.get(str(key))


def polygons_for(keys: list[str]) -> list[Neighborhood]:
    """The neighborhoods named by these keys, in the order given, skipping
    keys that don't exist (a stale key from the client is a no-op filter
    rather than an error)."""
    resolved = (get(key) for key in keys)
    return [n for n in resolved if n is not None]


def find_neighborhood(lat: float, lon: float) -> Optional[Neighborhood]:
    """The neighborhood polygon containing this point, or None. Coverage is
    high but not total, so a point on a highway, in a park or out on the
    fringe of the city legitimately falls inside none of them."""
    point = Point(lon, lat)
    for neighborhood in NEIGHBORHOODS:
        if neighborhood.min_lat <= lat <= neighborhood.max_lat and neighborhood.min_lon <= lon <= neighborhood.max_lon:
            if neighborhood.polygon.contains(point):
                return neighborhood
    return None


def contains_any(lat: float, lon: float, keys: list[str]) -> bool:
    """Whether the point falls inside any of the named neighborhoods. Used as
    the hard area filter -- the selected neighborhoods are a boundary on the
    map, so membership has to be decided by geometry, not by comparing a
    listing's stored neighborhood label."""
    point = Point(lon, lat)
    for neighborhood in polygons_for(keys):
        if neighborhood.min_lat <= lat <= neighborhood.max_lat and neighborhood.min_lon <= lon <= neighborhood.max_lon:
            if neighborhood.polygon.contains(point):
                return True
    return False


# How far around a named landmark still counts as "that area". A محله is
# roughly 800 m across, so this reaches the ones whose edge the landmark sits
# on without spilling across the city -- "محدوده تئاتر شهر" should mean the
# blocks you can walk to from it, not منطقه ۱۱ entire.
_VICINITY_METERS = 700.0
_MAX_VICINITY_KEYS = 4


def _to_metres(lat0: float):
    """A local equirectangular projection centred on this latitude.

    Distances have to be compared in metres, and a degree of longitude at
    Tehran's 35.7 deg is only ~0.81 of a degree of latitude, so measuring in
    raw degrees would stretch the radius north-south by a quarter.
    """
    import math

    scale = math.cos(math.radians(lat0))

    def project(lon: float, lat: float) -> tuple[float, float]:
        return (lon * _METERS_PER_DEGREE_LAT * scale, lat * _METERS_PER_DEGREE_LAT)

    return project


def keys_near(
    lat: float, lon: float, radius_m: float = _VICINITY_METERS, limit: int = _MAX_VICINITY_KEYS
) -> list[str]:
    """The neighborhoods at or within `radius_m` of a point, nearest first.

    A landmark is a point and a search area is a region, so naming one has to
    turn into several محله: someone who says "محدوده تئاتر شهر" will happily
    look at the block across the street, which is a different polygon.
    """
    from shapely.ops import transform

    project = _to_metres(lat)
    point = transform(project, Point(lon, lat))
    margin = radius_m / _METERS_PER_DEGREE_LAT * 1.3

    scored: list[tuple[float, str]] = []
    for neighborhood in NEIGHBORHOODS:
        if not (
            neighborhood.min_lat - margin <= lat <= neighborhood.max_lat + margin
            and neighborhood.min_lon - margin <= lon <= neighborhood.max_lon + margin
        ):
            continue
        distance = transform(project, neighborhood.polygon).distance(point)
        if distance <= radius_m:
            scored.append((distance, neighborhood.key))

    scored.sort()
    return [key for _, key in scored[:limit]]


def _resolve_by_title(name: str) -> Optional[str]:
    """The neighborhood actually called this, or None. Titles are the only
    unambiguous signal -- everything else is a landmark that may sit in one
    محله while being named by another."""
    needle = _squash(name)
    if not needle:
        return None
    exact = _BY_TITLE.get(needle) or _BY_BASE_TITLE.get(needle)
    if exact is not None:
        return exact.key
    if len(needle) < 3:
        return None

    tokens = [token for token in (_squash(part) for part in _norm(name).split(" ")) if len(token) >= 3]
    for token in tokens:
        match = _BY_TITLE.get(token) or _BY_BASE_TITLE.get(token)
        if match is not None:
            return match.key

    for title, neighborhood in _BY_TITLE.items():
        if len(title) >= _MIN_CONTAINMENT_LENGTH and (title in needle or needle in title):
            return neighborhood.key
    return None


def _resolve_by_keyword(name: str) -> Optional[str]:
    """The weakest signal: a محله that merely lists this street or landmark
    among its keywords. Streets like دماوند run through several, so this is
    consulted only once titles and the gazetteer have both failed."""
    needle = _squash(name)
    if not needle:
        return None
    match = _BY_KEYWORD.get(needle)
    if match is not None:
        return match.key

    tokens = [token for token in (_squash(part) for part in _norm(name).split(" ")) if len(token) >= 3]
    for token in tokens:
        match = _BY_KEYWORD.get(token)
        if match is not None:
            return match.key

    for keyword, neighborhood in _BY_KEYWORD.items():
        if len(keyword) >= _MIN_CONTAINMENT_LENGTH and (keyword in needle or needle in keyword):
            return neighborhood.key
    return None


@lru_cache(maxsize=512)
def resolve_area(name: str) -> tuple[str, ...]:
    """Map one Persian place name onto the neighborhood keys it means.

    A name can be three different things and each is answered differently:

    * a محله ("نارمک") -- one polygon, by title;
    * a landmark, square or campus ("تئاتر شهر", "میدان انقلاب") -- a *point*,
      which becomes the polygon it falls in plus the ones a short walk away;
    * a street ("خیابان دماوند") -- no point and no title, only the keyword
      lists, which is a guess and treated as the last resort it is.

    The gazetteer deliberately outranks the keyword lists. Going the other way
    round is what made "انقلاب" resolve to بهارستان: a neighborhood two
    kilometres from میدان انقلاب that happens to name an انقلاب street among
    its keywords. Returns () when nothing matches -- the caller drops the term
    rather than guessing, since the area is a hard filter and a wrong guess
    silently empties the result set.
    """
    key = _resolve_by_title(name)
    if key is not None:
        return (key,)

    landmark = landmarks.resolve(name)
    if landmark is not None:
        nearby = keys_near(landmark.lat, landmark.lon)
        if nearby:
            return tuple(nearby)

    key = _resolve_by_keyword(name)
    return (key,) if key is not None else ()


def resolve_name(name: str) -> Optional[str]:
    """The single best neighborhood key for a name, or None."""
    keys = resolve_area(name)
    return keys[0] if keys else None


def resolve_names(names: list[str]) -> list[str]:
    """Resolve free-text Persian names (from the LLM or a URL) to unique
    neighborhood keys, preserving order and dropping anything unmatched."""
    keys: list[str] = []
    for name in names:
        for key in resolve_area(name):
            if key not in keys:
                keys.append(key)
    return keys


def normalize_keys(values: list[str]) -> list[str]:
    """Accept either keys or Persian titles from the client and return keys.

    The UI sends keys, but chat-extracted intent and hand-written URLs carry
    names; normalizing here means callers never have to know which they hold.
    """
    keys: list[str] = []
    for value in values:
        resolved = (value,) if value in _BY_KEY else resolve_area(value)
        for key in resolved:
            if key not in keys:
                keys.append(key)
    return keys
